gpu: 1
dataroot: ../routability_ir_drop_prediction/training_set_N14/DRC
save_path: ./work_dirs/RouteNet_N14_biased_loss_30k
max_iters: 30000
ann_file_train: ./files/train_N14_train.csv
ann_file_val: ./files/train_N14_val.csv
model_type: RouteNet
batch_size: 8
in_channels: 9
out_channels: 1
lr: 0.0002
weight_decay: 0.0001
loss_type: BiasedLoss
biased_loss_s: 20
biased_loss_b: 0.4
threshold: 0.1
eval_metric:
- NRMS
- SSIM
save_freq: 5000
eval_freq_epochs: 1
ann_file_test: ./files/test_N14.csv
plot_roc: true
seed: 0
pretrained: ./work_dirs/RouteNet_N14_biased_loss_30k/model_iters_30000.pth